// Rebuild the self-contained plugin from local sources; no downloads or dependencies.
import {readFile,writeFile} from 'node:fs/promises';
const here=new URL('./',import.meta.url);
const tokens=JSON.parse(await readFile(new URL('../tokens.json',here),'utf8'));
const map=await readFile(new URL('./assets/map-preview.png',here));
const source=await readFile(new URL('./src.js',here),'utf8');
await writeFile(new URL('./code.js',here),`// Generated by build.mjs. Local embedded assets only.\nconst TOKENS = ${JSON.stringify(tokens)};\nconst MAP_BASE64 = ${JSON.stringify(map.toString('base64'))};\n${source}`);
console.log('Built self-contained code.js');
