/* global figma, TOKENS, MAP_BASE64 */
// Generates only new pages and new styles. No existing nodes or styles are edited.
const C=TOKENS.colors;
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const paint=h=>[{type:'SOLID',color:rgb(h)}];
let font, bold, mapHash, page, prefix;
const styles={}, components={};
function frame(parent,name,x,y,w,h,color=C.panel){const n=figma.createFrame();parent.appendChild(n);n.name=name;n.resize(w,h);n.x=x;n.y=y;n.fills=color?paint(color):[];n.clipsContent=true;return n;}
function text(parent,name,value,x,y,w,size=14,color=C.text,strong=false){const n=figma.createText();parent.appendChild(n);n.name=name;n.fontName=strong?bold:font;n.fontSize=size;n.lineHeight={unit:'PIXELS',value:size*1.5};n.characters=value;n.fills=paint(color);n.resize(w,Math.ceil(size*1.5));n.textAutoResize='HEIGHT';n.x=x;n.y=y;return n;}
function rect(parent,name,x,y,w,h,color,radius=6){const n=figma.createRectangle();parent.appendChild(n);n.name=name;n.resize(w,h);n.x=x;n.y=y;n.fills=paint(color);n.cornerRadius=radius;return n;}
function stack(n,direction='HORIZONTAL',gap=8,padding=12){n.layoutMode=direction;n.primaryAxisSizingMode='AUTO';n.counterAxisSizingMode='AUTO';n.itemSpacing=gap;n.paddingLeft=padding;n.paddingRight=padding;n.paddingTop=padding;n.paddingBottom=padding;n.counterAxisAlignItems='CENTER';}
function base64(s){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';const out=[];let acc=0,bits=0;for(const ch of s){const v=alphabet.indexOf(ch);if(v<0)continue;acc=(acc<<6)|v;bits+=6;if(bits>=8){bits-=8;out.push((acc>>bits)&255);}}return new Uint8Array(out);}
function image(parent,name,x,y,w,h){const n=rect(parent,name,x,y,w,h,C.background,6);n.fills=[{type:'IMAGE',imageHash:mapHash,scaleMode:'FILL'}];return n;}
function instance(parent,key,label,x,y,w){const n=components[key].createInstance();parent.appendChild(n);n.x=x;n.y=y;n.name=key+'/'+label;const t=n.findOne(z=>z.type==='TEXT'&&z.name==='Label');if(t)t.characters=label;if(w)n.resize(w,n.height);return n;}
function button(p,label,x,y,w=112,kind='Secondary'){return instance(p,'Button/'+kind,label,x,y,w);}
function chip(p,label,x,y,selected=false,w=128){return instance(p,'Category/'+(selected?'Selected':'Default'),label,x,y,w);}
function tag(p,label,x,y,selected=false,w=86){return instance(p,'Tag/'+(selected?'Selected':'Default'),label,x,y,w);}
function note(p,value,x,y,w){return text(p,'Annotation',value,x,y,w,12,C.muted);}
async function chooseFonts(){const available=await figma.listAvailableFontsAsync();const preferred=TOKENS.typography.preferredFamilies.concat(['Noto Sans CJK SC','Arial Unicode MS','Inter']);for(const family of preferred){const options=available.filter(f=>f.fontName.family===family);const regular=options.find(f=>/regular|normal|book/i.test(f.fontName.style))||options[0];if(!regular)continue;try{await figma.loadFontAsync(regular.fontName);font=regular.fontName;const heavy=options.find(f=>/semibold|bold|medium/i.test(f.fontName.style));bold=font;if(heavy){try{await figma.loadFontAsync(heavy.fontName);bold=heavy.fontName;}catch{}}return;}catch{}}throw new Error('没有可加载字体。请安装 Noto Sans SC，重启 Figma 后重试。');}
function component(parent,name,label,w,bg,fg){const n=figma.createComponent();parent.appendChild(n);n.name=name;n.resize(w,40);n.fills=paint(bg);n.strokes=paint(C.border);n.strokeWeight=1;n.cornerRadius=6;stack(n,'HORIZONTAL',8,10);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';n.primaryAxisAlignItems='CENTER';text(n,'Label',label,0,0,w-20,14,fg);return n;}
function library(){const board=frame(page,'00 / Components & tokens',0,0,1600,1020);text(board,'Title','POWER WARDS / DESIGN SYSTEM',32,24,1200,26,C.amber,true);note(board,'原生组件与自动布局 · 修改主组件可复用到所有状态 · 示例内容不代表真实眼位攻略',32,70,1400);
let sx=32;Object.entries(C).forEach(([name,color])=>{rect(board,'Swatch/'+name,sx,120,126,48,color);note(board,name+'\n'+color,sx,176,126);const style=figma.createPaintStyle();style.name=prefix+'/Color/'+name;style.paints=paint(color);styles[name]=style;sx+=150;});
Object.entries(TOKENS.typography.sizes).forEach(([name,size])=>{const s=figma.createTextStyle();s.name=prefix+'/Type/'+name;s.fontName=font;s.fontSize=size;s.lineHeight={unit:'PERCENT',value:150};});
const families=[['Button',[['Primary','保存',C.amber,C.background],['Secondary','另存为',C.raised,C.text],['Hover','保存', '#FFD596',C.background],['Disabled','保存',C.raised,C.muted]]],['Category',[['Default','□ 天辉防守',C.raised,C.text],['Selected','✓ 天辉进攻','#253C45',C.cyan]]],['Tag',[['Default','河道',C.raised,C.muted],['Selected','需要砍树 ×','#39352D',C.amber]]],['Profile',[['Default','我的常用眼位  ▾',C.raised,C.text],['Open','我的常用眼位  ▴','#303C43',C.amber]]]];
families.forEach(([family,variants],row)=>{note(board,family,32,270+row*116,200);const nodes=variants.map(([state,label,bg,fg],i)=>{const n=component(board,'State='+state,label,family==='Profile'?228:156,bg,fg);n.x=32+i*250;n.y=300+row*116;components[family+'/'+state]=n;return n;});const set=figma.combineAsVariants(nodes,board);set.name='PW/'+family;set.layoutMode='HORIZONTAL';set.itemSpacing=24;set.paddingLeft=16;set.paddingRight=16;set.paddingTop=16;set.paddingBottom=16;set.x=32;set.y=300+row*116;});
const markers=[];['cyan','coral','amber'].forEach((color,i)=>{const n=figma.createComponent();board.appendChild(n);n.name='Tone='+color;n.resize(40,40);n.fills=[];const outer=figma.createEllipse();n.appendChild(outer);outer.resize(32,32);outer.x=4;outer.y=4;outer.fills=paint(C.background);outer.strokes=paint(C[color]);outer.strokeWeight=2;const eye=figma.createEllipse();n.appendChild(eye);eye.resize(22,13);eye.x=9;eye.y=13;eye.fills=paint(C[color]);const pupil=figma.createEllipse();n.appendChild(pupil);pupil.resize(8,8);pupil.x=16;pupil.y=15.5;pupil.fills=paint(C.background);n.x=32+i*80;n.y=824;components['Ward/'+color]=n;markers.push(n);});const set=figma.combineAsVariants(markers,board);set.name='PW/WardMarker';set.x=32;set.y=824;note(board,'颜色独立于分类。标记位置仅为视觉示例。字体：'+font.family+' / '+font.style,32,900,1400);return board;}
function header(root,dirty){const h=frame(root,'Header / Save actions',0,0,1600,64,C.background);rect(h,'Brand mark',24,20,24,24,C.amber,4);text(h,'Brand','POWER WARDS',62,14,260,24,C.amber,true);text(h,'Product','眼位地图编辑器',338,22,240,14,C.muted);text(h,'Save status',dirty?'● 未保存':'已保存到本机',1040,22,140,14,dirty?C.amber:C.muted);button(h,'保存',1192,12,112);button(h,'另存为',1316,12,112);button(h,'导出 JSON',1440,12,136,'Primary');}
function sidebar(root){const p=frame(root,'Sidebar / Current profile & filters',0,64,288,936);text(p,'Profile label','PROFILE',24,24,240,12,C.muted);instance(p,'Profile/Default','我的常用眼位  ▾',24,54,240);button(p,'导入 Profile',24,108,240);button(p,'新建 / 管理',24,160,240);rect(p,'Divider',24,228,240,1,C.border,0);text(p,'Filters','筛选',24,252,240,20,C.text,true);note(p,'适用分类 · 独立组合多选',24,298,240);['天辉进攻','天辉防守','夜魇进攻','夜魇防守'].forEach((s,i)=>chip(p,'✓ '+s,24,332+i*50,true,240));note(p,'自定义标签',24,558,240);tag(p,'需要砍树',24,590,true,110);tag(p,'河道',146,590,false,110);tag(p,'高台',24,636,false,110);button(p,'清除筛选',24,706,240);text(p,'Result count','显示 8 / 24 个眼位',24,772,240,14,C.amber);note(p,'仅显示当前 Profile\n截图只保存在当前设备',24,850,240);}
const points=[[.44,.22,'cyan'],[.72,.30,'coral'],[.29,.42,'cyan'],[.30,.61,'coral'],[.58,.62,'amber'],[.42,.73,'cyan'],[.74,.81,'coral'],[.84,.92,'cyan']];
function mapPanel(root,selected,expand){const width=expand?1312:960;const p=frame(root,'Map / Relative-coordinate overlay',288,64,width,936,C.background);const mapW=960,mapH=960*8424/8909;const offset=(width-mapW)/2;const world=frame(p,'MapWorld / Zoom illustration',offset,0,mapW,mapH,null);const n=image(world,'Map / 7.41 raster',0,0,mapW,mapH);n.fills=[{type:'IMAGE',imageHash:mapHash,scaleMode:'FILL'}];points.forEach(([x,y,color],i)=>{const dot=instance(world,'Ward/'+color,'示例眼位 '+(i+1),x*mapW-20,y*mapH-20);dot.setPluginData('relativeCoordinate',JSON.stringify({x,y}));if(selected&&i===4){const ring=figma.createEllipse();world.appendChild(ring);ring.name='Selection ring';ring.resize(52,52);ring.x=x*mapW-26;ring.y=y*mapH-26;ring.fills=[];ring.strokes=paint(C.amber);ring.strokeWeight=2;}});if(selected){world.rescale(1.18);world.x=offset-100;world.y=-100;}// Illustrative focus only; not a specified runtime zoom.
button(p,'＋ 添加眼位',20,20,150,'Primary');const help=frame(p,'Map / Interaction hint',16,884,width-32,36,C.background);note(help,'Ctrl + 左键添加 · 滚轮缩放 · 拖动平移 · 右键全图',12,8,width-280);button(p,'−   缩放   ＋',width-240,838,132);button(p,'全图',width-96,838,76);return p;}
function details(root){const p=frame(root,'Inspector / Selected ward',1248,64,352,936);text(p,'Ward name','河道高台眼',24,20,266,22,C.text,true);text(p,'Close','×',306,20,24,22,C.muted);const crop=frame(p,'Screenshot / Local illustrative crop',24,70,304,198,C.background);image(crop,'Map crop / NOT a gameplay screenshot',-120,-180,720,682);const badge=frame(crop,'Illustration label',8,164,288,26,C.background);note(badge,'示意图 · 地图裁切，非实战截图',8,4,272);button(p,'上传本地截图',24,280,144);button(p,'更换图片',180,280,148);note(p,'标记颜色',24,338,280);['cyan','amber','coral','teal'].forEach((c,i)=>rect(p,'Color/'+c,24+i*62,370,42,34,C[c]));note(p,'适用分类 · 可多选',24,426,300);['天辉进攻','天辉防守','夜魇进攻','夜魇防守'].forEach((s,i)=>chip(p,(i===0||i===3?'✓ ':'□ ')+s,24+(i%2)*158,460+Math.floor(i/2)*48,i===0||i===3,146));note(p,'自定义标签',24,566,304);tag(p,'需要砍树 ×',24,600,true,142);tag(p,'高台 ×',178,600,true,150);button(p,'＋ 添加标签',24,650,304);note(p,'详细说明',24,708,304);const field=frame(p,'Description / Editable text',24,742,304,106,C.background);field.cornerRadius=6;text(field,'Description','示例：插眼前清理入口树木；插眼后再砍下方一棵树，扩大河道视野。\n请使用自己的实战截图核对位置。',12,10,280,14);note(p,'图片不随 JSON 分享文件导出。',24,870,304);}
function addPanel(p){const panel=frame(p,'Overlay / New ward classification',170,638,620,188,C.panel);panel.cornerRadius=10;panel.strokes=paint(C.border);text(panel,'Title','新增眼位',20,16,500,18,C.text,true);note(panel,'可选多个适用组合',20,48,500);['天辉进攻','天辉防守','夜魇进攻','夜魇防守'].forEach((s,i)=>chip(panel,(i===0||i===3?'✓ ':'□ ')+s,20+i*148,80,i===0||i===3,136));button(panel,'取消',364,132,108);button(panel,'确认',484,132,116,'Primary');}
function modal(root,kind){const shade=rect(root,'Overlay / Scrim',0,64,1600,936,'#000000',0);shade.opacity=.65;const management=kind==='profiles';const box=frame(root,management?'Dialog / Profile management':'Dialog / Unsaved changes',management?470:510,management?228:344,management?660:580,management?536:286,C.panel);box.cornerRadius=12;box.strokes=paint(C.border);text(box,'Title',management?'Profile 管理':'保存当前修改？',28,24,580,24,C.text,true);if(management){note(box,'每次只显示一个 Profile。导入的是可编辑本地副本。',28,70,604);['我的常用眼位 · 当前','朋友的河道眼位 · 本地副本','职业选手眼位笔记 · 本地副本'].forEach((s,i)=>{const row=frame(box,'Profile row / '+i,28,114+i*82,604,68,i===0?'#333329':C.raised);text(row,'Name',s,16,12,410,16);note(row,'可直接编辑 · 保存 · 另存为',16,38,400);button(row,i===0?'当前':'切换',490,14,98,i===0?'Primary':'Secondary');});button(box,'＋ 新建',28,394,180);button(box,'导入 JSON',220,394,180);button(box,'关闭',412,394,220);note(box,'导入新建独立 Profile，不覆盖现有资料。',28,470,604);}else{note(box,'“我的常用眼位”有未保存的修改。\n保存后继续，或放弃本次修改。取消将留在当前界面。',28,78,524);button(box,'取消',28,194,150);button(box,'放弃修改',190,194,170);button(box,'保存并继续',372,194,180,'Primary');}}
function screen(name,x,y,mode){const root=frame(page,name,x,y,1600,1000,C.background);header(root,mode!=='browse');sidebar(root);const map=mapPanel(root,mode==='detail',mode==='browse');if(mode!=='browse')details(root);if(mode==='add')addPanel(map);if(mode==='profiles'||mode==='unsaved')modal(root,mode);root.setPluginData('designStatus','Editable design proposal; not application implementation');return root;}
async function run(){await chooseFonts();mapHash=figma.createImage(base64(MAP_BASE64)).hash;page=figma.createPage();const stamp=new Date().toISOString().replace(/[:.]/g,'-');page.name='Power Wards / Design Kit / '+stamp;await figma.setCurrentPageAsync(page);prefix='PW '+stamp;library();const screens=[screen('01 / Browse / No selection',0,1180,'browse'),screen('02 / Selected ward / Focus',1720,1180,'detail'),screen('03 / Add ward / Classification',3440,1180,'add'),screen('04 / Profile management',0,2380,'profiles'),screen('05 / Unsaved changes / App navigation',1720,2380,'unsaved')];const notes=frame(page,'06 / Agent handoff & constraints',3440,2380,1600,1000);text(notes,'Title','AI AGENT / HANDOFF',40,32,1450,28,C.amber,true);text(notes,'Requirements','来源：REQUIREMENTS.md 是业务规则真源。\n\n01 未选中时不显示右侧详情；02 展示聚焦设计示意，倍率待定。\n03 四个分类是独立组合，可任意多选，不做阵营×用途交叉推导。\n04 任意 Profile 可直接编辑、保存、另存为，仅单 Profile 显示。\n05 此三选项用于应用内导航/桌面；浏览器关闭只能使用允许的离开保护。\n\n截图在本机保存；JSON 分享全部文字、坐标、颜色、分类、标签与必要元数据，不带图片。\n地图上的位置与说明为视觉示例，不是真实攻略。局部图是地图裁切示意。\n标签多选 AND/OR、聚焦倍率、移动/删除/撤销仍待确认。\n\n设计：1600×1000；三栏 288 / 960 / 352；未选中时地图扩展。\n色彩与字号见 00 组件库及 tokens.json。所有文字可编辑，地图为栅格填充。\n组件使用 PW/ 前缀；标记通过 relativeCoordinate pluginData 提供归一化示例位置。\n\n这是静态可编辑设计状态，不包含交互原型连线，也不是应用实现。\n运行仅新建设计页和本地样式，不改动已有页。\n本生成器未在真实 Figma 中执行验证，请导入后检查中文、溢出与图片。',40,106,1480,20);figma.currentPage.selection=[screens[1]];figma.viewport.scrollAndZoomIntoView([screens[1]]);figma.closePlugin('已生成 Power Wards 设计页。使用字体：'+font.family);}
run().catch(e=>{console.error(e);figma.closePlugin('生成失败：'+e.message+'。已有页面未修改；若新页部分生成，可检查或手动删除该新页。');});
